# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

#daemon off;

error_log   /var/log/nginx/error.log;

worker_processes  1;

pid        /tmp/nginx.pid;

events {
  worker_connections 1024;
}

http {
	client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

	include           /etc/nginx/mime.types;
	default_type      application/octet-stream;

	# Turn off buffering to temp files
	proxy_buffering off;

	keepalive_timeout 120;

  sendfile on;

	gzip on;
	gzip_http_version 1.1;
	gzip_disable      "MSIE [1-6]\.";
	gzip_min_length   256;
	gzip_vary         on;
	gzip_proxied      expired no-cache no-store private auth;
	gzip_types        text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
	gzip_comp_level   9;

	server_names_hash_bucket_size 128;

	# These two should be the same or nginx will start writing
	#  large request bodies to temp files
	client_body_buffer_size 10m;
	client_max_body_size    10m;

	access_log /dev/stdout;

	index index.html index.htm;

	server {
        listen       4443 ssl;
        #listen       [::]:4443 ssl http2 default_server;
		server_name  _;
		root         /usr/share/nginx/html;

        ssl_certificate "/etc/ssl/certs/PrakCode-self-sign/tls.crt";
        ssl_certificate_key "/etc/ssl/certs/PrakCode-self-sign/tls.key";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers 
EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
        ssl_prefer_server_ciphers on;

		# Load configuration files for the default server block.
		include /etc/nginx/default.d/*.conf;

		location / {
			root /usr/share/nginx/html;
			expires -1;
			try_files $uri /index.html;
		}

		error_page 404 /404.html;
			location = /40x.html {
		}

		error_page 500 502 503 504 /50x.html;
			location = /50x.html {
		}
	}
}
