// native_rust.rs
// Auto-generated by GraalVM Optimizer
// Target: Rust -- HashMap counting pattern matches K-NUCLEOTIDE benchmark where Rust's safe hash maps provide significant energy efficiency
// Energy saving: ~42% vs original
// Compile: rustc --emit=llvm-bc -O --crate-type=cdylib native_rust.rs -o native_rust.bc
#![allow(non_snake_case, dead_code, unused_variables)]
use std::f64;

use std::collections::HashMap;
use std::ffi::CStr;
use std::os::raw::c_char;
use std::os::raw::c_long;

#[no_mangle]
pub extern "C" fn count_word_frequency(
    words_flat: *const c_char,
    n: i32,
    stride: i32,
    keys_out: *mut c_char,
    key_stride: i32,
    values_out: *mut i32,
    max_entries: i32,
) -> i32 {
    let mut freq: HashMap<String, i32> = HashMap::new();
    
    for i in 0..n {
        let offset = (i * stride) as isize;
        let word_ptr = unsafe { words_flat.offset(offset) };
        let word_cstr = unsafe { CStr::from_ptr(word_ptr) };
        if let Ok(word) = word_cstr.to_str() {
            let lower_word = word.to_lowercase();
            *freq.entry(lower_word).or_insert(0) += 1;
        }
    }
    
    let mut count = 0;
    for (key, value) in freq.iter() {
        if count >= max_entries {
            break;
        }
        let key_bytes = key.as_bytes();
        let copy_len = std::cmp::min(key_bytes.len(), (key_stride - 1) as usize);
        unsafe {
            let key_dest = keys_out.offset((count * key_stride) as isize);
            std::ptr::copy_nonoverlapping(key_bytes.as_ptr() as *const c_char, key_dest, copy_len);
            *key_dest.offset(copy_len as isize) = 0;
            *values_out.offset(count as isize) = *value;
        }
        count += 1;
    }
    count
}

#[no_mangle]
pub extern "C" fn count_kmers(
    sequence: *const c_char,
    k: i32,
    keys_out: *mut c_char,
    key_stride: i32,
    values_out: *mut i32,
    max_entries: i32,
) -> i32 {
    let seq_cstr = unsafe { CStr::from_ptr(sequence) };
    let seq_str = match seq_cstr.to_str() {
        Ok(s) => s,
        Err(_) => return 0,
    };
    
    let mut counts: HashMap<String, i32> = HashMap::new();
    let seq_len = seq_str.len() as i32;
    
    for i in 0..=(seq_len - k) {
        let start = i as usize;
        let end = (i + k) as usize;
        if end <= seq_str.len() {
            let kmer = &seq_str[start..end];
            *counts.entry(kmer.to_string()).or_insert(0) += 1;
        }
    }
    
    let mut count = 0;
    for (key, value) in counts.iter() {
        if count >= max_entries {
            break;
        }
        let key_bytes = key.as_bytes();
        let copy_len = std::cmp::min(key_bytes.len(), (key_stride - 1) as usize);
        unsafe {
            let key_dest = keys_out.offset((count * key_stride) as isize);
            std::ptr::copy_nonoverlapping(key_bytes.as_ptr() as *const c_char, key_dest, copy_len);
            *key_dest.offset(copy_len as isize) = 0;
            *values_out.offset(count as isize) = *value;
        }
        count += 1;
    }
    count
}

#[repr(C)]
struct TreeNode {
    val: i32,
    left: *mut TreeNode,
    right: *mut TreeNode,
}

#[no_mangle]
pub extern "C" fn compute_tree_depth(root_ptr: c_long) -> i32 {
    if root_ptr == 0 {
        return 0;
    }
    
    let root = unsafe { &*(root_ptr as *const TreeNode) };
    
    let left_depth = compute_tree_depth(root.left as c_long);
    let right_depth = compute_tree_depth(root.right as c_long);
    
    1 + std::cmp::max(left_depth, right_depth)
}

#[repr(C)]
struct TreeNode {
    val: i32,
    left: *mut TreeNode,
    right: *mut TreeNode,
}

#[no_mangle]
pub extern "C" fn sum_tree_values(root_ptr: c_long) -> c_long {
    if root_ptr == 0 {
        return 0;
    }
    
    let root = unsafe { &*(root_ptr as *const TreeNode) };
    
    let left_sum = sum_tree_values(root.left as c_long);
    let right_sum = sum_tree_values(root.right as c_long);
    
    (root.val as c_long) + left_sum + right_sum
}