package com.example;
import java.util.*;

// Auto-generated by GraalVM Optimizer - polyglot runtime bridge
import org.graalvm.polyglot.*;
import java.io.File;
import java.util.HashMap;
import java.util.HashSet;

class _GraalContext {
    private static Context ctx;
    private static final HashMap<String, Value> modules = new HashMap<>();
    private static final HashSet<String> failed = new HashSet<>();
    static final String NATIVE_DIR;

    static {
        String nd = System.getProperty("native.dir");
        if (nd == null) nd = System.getProperty("user.dir") + "/native";
        NATIVE_DIR = nd;
        try {
            ctx = Context.newBuilder()
                .allowAllAccess(true)
                .option("engine.WarnInterpreterOnly", "false")
                .build();
        } catch (Exception e) {
            ctx = null;
            System.err.println("[GraalVM] Could not create context: " + e.getMessage());
        }
    }

    static boolean isAvailable() { return ctx != null; }

    static Value loadLLVM(String name) {
        if (modules.containsKey(name)) return modules.get(name);
        if (failed.contains(name) || ctx == null) return null;
        try {
            File bc = new File(NATIVE_DIR + "/" + name + ".bc");
            Source src = Source.newBuilder("llvm", bc).build();
            ctx.eval(src);
            Value bindings = ctx.getBindings("llvm");
            modules.put(name, bindings);
            return bindings;
        } catch (Exception e) {
            System.err.println("[GraalVM] Failed to load " + name + ".bc: " + e.getMessage());
            failed.add(name);
            return null;
        }
    }

    static Value fn(String module, String funcName) {
        Value mod = loadLLVM(module);
        if (mod == null) return null;
        return mod.getMember(funcName);
    }
}
// ---------------------------------------------------------------------------


/**
 * Test file for Rust recommendation verification.
 * Contains HashMap counting and binary tree functions
 * that should be recommended for Rust conversion.
 */
public class DataProcessor {

    // ── GraalVM native module handles (auto-generated) ──────────────
    static final org.graalvm.polyglot.Value _lib_native_rust = _GraalContext.loadLLVM("native_rust");


    // HashMap counting â€” should recommend Rust
    public Map<String, Integer> countWordFrequency(String[] words) {
        // [GraalVM -> Rust] HashMap counting pattern matches K-NUCLEOTIDE benchmark where Rust's safe hash maps provide significant energy efficiency
        org.graalvm.polyglot.Value _lib = _GraalContext.loadLLVM("native_rust");
        if (_lib != null) {
            org.graalvm.polyglot.Value _fn_countWordFrequency = _lib.getMember("countWordFrequency");
            if (_fn_countWordFrequency != null) {
                // Flat array output buffer: Java allocates, native fills, Java reconstructs
                int _maxEntries = 4096;
                int _keyStride  = 64;
                byte[] _keyBuf = new byte[_maxEntries * _keyStride];
                int[] _valBuf = new int[_maxEntries];
                byte[] _words_flat = new byte[words.length * _keyStride];
                for (int _fi = 0; _fi < words.length; _fi++) {
                    byte[] _fb = words[_fi].getBytes(java.nio.charset.StandardCharsets.UTF_8);
                    System.arraycopy(_fb, 0, _words_flat, _fi * _keyStride, Math.min(_fb.length, _keyStride - 1));
                }
                org.graalvm.polyglot.Value _fnVal = _lib.getMember("countWordFrequency");
                if (_fnVal != null) {
                    int _nEntries = (int) _fnVal.execute(_words_flat, words.length, _keyStride, _keyBuf, _keyStride, _valBuf, _maxEntries).asLong();
                    java.util.Map<String, Integer> _res = new java.util.HashMap<>(_nEntries);
                    for (int _i = 0; _i < _nEntries; _i++) {
                        String _k = new String(_keyBuf, _i * _keyStride, _keyStride, java.nio.charset.StandardCharsets.UTF_8).replace("\0", "").strip();
                        _res.put(_k, _valBuf[_i]);
                    }
                    return _res;
                }
            }
        }
        // Java fallback:

        Map<String, Integer> freq = new HashMap<>();
        for (String word : words) {
            freq.merge(word.toLowerCase(), 1, Integer::sum);
        }
        return freq;
    }

    // K-mer counting â€” should recommend Rust
    public Map<String, Integer> countKmers(String sequence, int k) {
        // [GraalVM -> Rust] K-mer counting is classic K-NUCLEOTIDE pattern where Rust's safe hash maps excel over Java HashMap
        org.graalvm.polyglot.Value _lib = _GraalContext.loadLLVM("native_rust");
        if (_lib != null) {
            org.graalvm.polyglot.Value _fn_countKmers = _lib.getMember("countKmers");
            if (_fn_countKmers != null) {
                // Flat array output buffer: Java allocates, native fills, Java reconstructs
                int _maxEntries = 4096;
                int _keyStride  = 64;
                byte[] _keyBuf = new byte[_maxEntries * _keyStride];
                int[] _valBuf = new int[_maxEntries];
                org.graalvm.polyglot.Value _fnVal = _lib.getMember("countKmers");
                if (_fnVal != null) {
                    int _nEntries = (int) _fnVal.execute(sequence, k, _keyBuf, _keyStride, _valBuf, _maxEntries).asLong();
                    java.util.Map<String, Integer> _res = new java.util.HashMap<>(_nEntries);
                    for (int _i = 0; _i < _nEntries; _i++) {
                        String _k = new String(_keyBuf, _i * _keyStride, _keyStride, java.nio.charset.StandardCharsets.UTF_8).replace("\0", "").strip();
                        _res.put(_k, _valBuf[_i]);
                    }
                    return _res;
                }
            }
        }
        // Java fallback:

        Map<String, Integer> counts = new HashMap<>();
        for (int i = 0; i <= sequence.length() - k; i++) {
            String kmer = sequence.substring(i, i + k);
            counts.merge(kmer, 1, Integer::sum);
        }
        return counts;
    }

    // Binary tree operations â€” should recommend Rust
    public int computeTreeDepth(TreeNode root) {
        // [GraalVM -> Rust] Binary tree traversal matches BINARY-TREES benchmark where Rust's ownership model provides energy efficiency
        org.graalvm.polyglot.Value _lib = _GraalContext.loadLLVM("native_rust");
        if (_lib != null) {
            org.graalvm.polyglot.Value _fn_computeTreeDepth = _lib.getMember("computeTreeDepth");
            if (_fn_computeTreeDepth != null) {
                return (int) _fn_computeTreeDepth.execute(root).asLong();
            }
        }
        // Java fallback:

        if (root == null) return 0;
        return 1 + Math.max(
            computeTreeDepth(root.left),
            computeTreeDepth(root.right)
        );
    }

    // Tree sum â€” should recommend Rust
    public long sumTreeValues(TreeNode root) {
        // [GraalVM -> Rust] Tree traversal and accumulation matches BINARY-TREES benchmark pattern where Rust excels
        org.graalvm.polyglot.Value _lib = _GraalContext.loadLLVM("native_rust");
        if (_lib != null) {
            org.graalvm.polyglot.Value _fn_sumTreeValues = _lib.getMember("sumTreeValues");
            if (_fn_sumTreeValues != null) {
                return (int) _fn_sumTreeValues.execute(root).asLong();
            }
        }
        // Java fallback:

        if (root == null) return 0;
        return root.val + sumTreeValues(root.left) + sumTreeValues(root.right);
    }

    // Orchestration â€” should stay in Java
    public void processData(String[] words, String sequence, TreeNode tree) {
        Map<String, Integer> wordFreq = countWordFrequency(words);
        Map<String, Integer> kmers    = countKmers(sequence, 3);
        int depth = computeTreeDepth(tree);
        long sum  = sumTreeValues(tree);
        System.out.println("Words: " + wordFreq.size() +
                           " Kmers: " + kmers.size() +
                           " Depth: " + depth +
                           " Sum: " + sum);
    }

    public static class TreeNode {
        public int val;
        public TreeNode left, right;
        public TreeNode(int val) { this.val = val; }
    }
}