// Auto-generated by GraalVM Optimizer — demo entry point
import com.example.DataProcessor;
import java.util.Arrays;

public class Main {
    public static void main(String[] args) throws Exception {
        System.out.println("GraalVM Polyglot Optimizer -- DataProcessor Demo");
        System.out.println("Running all converted functions via GraalVM Sulong...\n");
        System.out.println("--- countWordFrequency() ---");
        System.out.println("  (no demo available for this pattern)");
        System.out.println();
        System.out.println("--- countKmers() ---");
        System.out.println("  (no demo available for this pattern)");
        System.out.println();
        System.out.println("--- computeTreeDepth() ---");
        System.out.println("  (no demo available for this pattern)");
        System.out.println();
        System.out.println("--- sumTreeValues() ---");
        System.out.println("  (no demo available for this pattern)");
        System.out.println();
        System.out.println("\nDone. Replace this demo with your own main class.");
    }
}
