"""
generator/code_generator.py
Takes ProgramAnalysis and original source code, produces a complete
polyglot package: native source files + modified orchestrator.
"""
import os, re, textwrap
from pathlib import Path
from analyzer.ai_analyzer import ProgramAnalysis, FunctionAnalysis, SUPPORTED_LANGUAGES, TARGET_LANGUAGES

# ── Polyglot injection templates per orchestrator language ────────────────────

PYTHON_POLYGLOT_HEADER = '''# ── GraalVM Polyglot Runtime ─────────────────────────────────────────────────
# Auto-generated by GraalVM Optimizer
# Original program preserved as orchestrator; hot functions run natively.
import sys, os
_POLYGLOT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "native")

try:
    import polyglot as _polyglot
    _GRAAL = True
except ImportError:
    _GRAAL = False
    import ctypes as _ctypes

def _load_native(name, lang="llvm"):
    """Load a native module — GraalVM polyglot or ctypes fallback."""
    if _GRAAL:
        bc = open(os.path.join(_POLYGLOT_DIR, name + ".bc"), "rb").read()
        return _polyglot.eval(language=lang, string=bc)
    else:
        # ctypes fallback for non-GraalVM environments
        so = os.path.join(_POLYGLOT_DIR, name + ".so")
        return _ctypes.CDLL(so)

def _load_js(name):
    if _GRAAL:
        src = open(os.path.join(_POLYGLOT_DIR, name + ".js")).read()
        return _polyglot.eval(language="js", string=src)
    else:
        raise RuntimeError("JavaScript polyglot requires GraalVM. Install from https://www.graalvm.org")

# ─────────────────────────────────────────────────────────────────────────────
'''

JAVA_POLYGLOT_HEADER = '''// Auto-generated by GraalVM Optimizer - polyglot runtime bridge
import org.graalvm.polyglot.*;
import java.io.File;
import java.util.HashMap;
import java.util.HashSet;

class _GraalContext {
    private static Context ctx;
    private static final HashMap<String, Value> modules = new HashMap<>();
    private static final HashSet<String> failed = new HashSet<>();
    static final String NATIVE_DIR;
    // Set -Dnative.disabled=true to force Java fallback path (used by BenchmarkSuite)
    static final boolean NATIVE_DISABLED =
        "true".equalsIgnoreCase(System.getProperty("native.disabled", "false"));

    static {
        String nd = System.getProperty("native.dir");
        if (nd == null) nd = System.getProperty("user.dir") + "/native";
        NATIVE_DIR = nd;
        if (!NATIVE_DISABLED) {
            try {
                ctx = Context.newBuilder()
                    .allowAllAccess(true)
                    .option("engine.WarnInterpreterOnly", "false")
                    .build();
            } catch (Exception e) {
                ctx = null;
                System.err.println("[GraalVM] Could not create context: " + e.getMessage());
            }
        }
    }

    static boolean isAvailable() { return ctx != null && !NATIVE_DISABLED; }

    static Value loadLLVM(String name) {
        if (NATIVE_DISABLED) return null;
        if (modules.containsKey(name)) return modules.get(name);
        if (failed.contains(name) || ctx == null) return null;
        try {
            File bc = new File(NATIVE_DIR + "/" + name + ".bc");
            Source src = Source.newBuilder("llvm", bc).build();
            ctx.eval(src);
            Value bindings = ctx.getBindings("llvm");
            modules.put(name, bindings);
            return bindings;
        } catch (Exception e) {
            System.err.println("[GraalVM] Failed to load " + name + ".bc: " + e.getMessage());
            failed.add(name);
            return null;
        }
    }

    static Value fn(String module, String funcName) {
        Value mod = loadLLVM(module);
        if (mod == null) return null;
        return mod.getMember(funcName);
    }
}
// ---------------------------------------------------------------------------
'''

JS_POLYGLOT_HEADER = '''// ── GraalVM Polyglot Runtime ─────────────────────────────────────────────
// Auto-generated by GraalVM Optimizer
const { execSync } = require('child_process');
const path = require('path');
const fs = require('fs');
const NATIVE_DIR = path.join(__dirname, 'native');

let _polyglot;
try {
    _polyglot = Polyglot;  // GraalVM built-in
} catch(e) {
    _polyglot = null;
}

function loadNative(name, lang = 'llvm') {
    if (!_polyglot) throw new Error('GraalVM required for polyglot. Install from https://www.graalvm.org');
    const bc = fs.readFileSync(path.join(NATIVE_DIR, name + '.bc'));
    return _polyglot.eval(lang, bc);
}
function loadJS(name) {
    if (!_polyglot) throw new Error('GraalVM required for polyglot.');
    const src = fs.readFileSync(path.join(NATIVE_DIR, name + '.js'), 'utf8');
    return _polyglot.eval('js', src);
}
// ─────────────────────────────────────────────────────────────────────────────
'''

RUBY_POLYGLOT_HEADER = '''# ── GraalVM Polyglot Runtime ─────────────────────────────────────────────
# Auto-generated by GraalVM Optimizer
require 'polyglot' rescue nil
NATIVE_DIR = File.join(File.dirname(File.expand_path(__FILE__)), 'native')

def load_native(name, lang: 'llvm')
  bc = File.binread(File.join(NATIVE_DIR, "#{name}.bc"))
  Polyglot.eval(lang, bc)
end
def load_js(name)
  src = File.read(File.join(NATIVE_DIR, "#{name}.js"))
  Polyglot.eval('js', src)
end
# ─────────────────────────────────────────────────────────────────────────────
'''

POLYGLOT_HEADERS = {
    "python":     PYTHON_POLYGLOT_HEADER,
    "java":       JAVA_POLYGLOT_HEADER,
    "javascript": JS_POLYGLOT_HEADER,
    "nodejs":     JS_POLYGLOT_HEADER,
    "ruby":       RUBY_POLYGLOT_HEADER,
    "r":          "# GraalVM polyglot for R — using .C() interop\n",
}

C_FILE_HEADER = '''/*
 * {filename}
 * Auto-generated by GraalVM Optimizer
 * Target: {target_lang} — {reason}
 * Paper: SLE'17 "Energy Efficiency Across Programming Languages"
 * Energy saving: ~{savings}% vs original
 *
 * Compile to LLVM bitcode:
 *   {compile_cmd}
 */
'''

JS_FILE_HEADER = '''/*
 * {filename}
 * Auto-generated by GraalVM Optimizer
 * Target: JavaScript (GraalJS) — {reason}
 * Energy saving: ~{savings}% vs original
 */
'''


RUST_FILE_HEADER = """// {filename}
// Auto-generated by GraalVM Optimizer
// Target: Rust -- {reason}
// Energy saving: ~{savings}% vs original
// Compile: rustc --emit=llvm-bc -O --crate-type=cdylib {filename} -o native_rust.bc
#![allow(non_snake_case, dead_code, unused_variables)]
use std::f64;

"""

def _build_flat_args(param_names: list, sig_line: str, result_lines: list, indent: str) -> str:
    """
    For each param in param_names, detect if it is a String[] in the Java signature.
    If so, emit Java code to flatten it to a stride-padded byte[] and rewrite the arg
    as (flat_bytes, n, _keyStride). Returns a comma-separated args string ready to pass
    to the native execute() call (trailing comma included when non-empty).
    """
    call_args = []
    for pname in param_names:
        is_string_array = bool(re.search(r'String\s*\[\]\s+' + re.escape(pname), sig_line))
        if is_string_array:
            flat_var = f"_{pname}_flat"
            result_lines.append(f"{indent}        byte[] {flat_var} = new byte[{pname}.length * _keyStride];")
            result_lines.append(f"{indent}        for (int _fi = 0; _fi < {pname}.length; _fi++) {{")
            result_lines.append(f"{indent}            byte[] _fb = {pname}[_fi].getBytes(java.nio.charset.StandardCharsets.UTF_8);")
            result_lines.append(f"{indent}            System.arraycopy(_fb, 0, {flat_var}, _fi * _keyStride, Math.min(_fb.length, _keyStride - 1));")
            result_lines.append(f"{indent}        }}")
            call_args += [flat_var, f"{pname}.length", "_keyStride"]
        else:
            call_args.append(pname)
    return (", ".join(call_args) + ", ") if call_args else ""


class PackageGenerator:
    def __init__(self, analysis: ProgramAnalysis, source_code: str,
                 source_file: str, output_dir: str):
        self.analysis = analysis
        self.source_code = source_code
        self.source_file = Path(source_file)
        self.output_dir = Path(output_dir)
        self.native_dir = self.output_dir / "native"
        self.source_lines = source_code.splitlines()

    def generate(self) -> dict:
        """Generate the complete polyglot package. Returns manifest."""
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.native_dir.mkdir(exist_ok=True)

        manifest = {
            "source_language": self.analysis.source_language,
            "source_file": str(self.source_file.name),
            "native_files": [],
            "orchestrator_file": "",
            "build_steps": [],
            "run_command": "",
        }

        # Group functions by target language
        native_groups = {}  # lang -> [FunctionAnalysis]
        for fn in self.analysis.functions:
            lang = fn.recommended_language
            if lang == "keep" or fn.is_orchestrator:
                continue
            if lang not in native_groups:
                native_groups[lang] = []
            native_groups[lang].append(fn)

        # Write native source files
        for lang, fns in native_groups.items():
            native_file = self._write_native_file(lang, fns)
            manifest["native_files"].append(native_file)
            manifest["build_steps"].append(self._build_step(lang, native_file))

        # Write modified orchestrator
        orch_file = self._write_orchestrator(native_groups)
        manifest["orchestrator_file"] = str(orch_file)

        # Write entry point (Main.java for Java library classes, etc.)
        self._write_entry_point()

        # Write test suite (runs during docker build, fails build if tests fail)
        self._write_test_suite(native_groups)

        # Write benchmark suite (run separately via docker run after build)
        self._write_benchmark_suite()
        self._write_benchmark_sh()

        # Write build script
        self._write_build_script(manifest)

        # Write run script
        run_script = self._write_run_script(manifest)
        manifest["run_command"] = str(run_script)

        # Write docker files
        self._write_dockerfile()
        self._write_docker_compose()

        # Write summary report
        self._write_report(manifest)

        return manifest

    def _write_entry_point(self):
        """
        For Java library classes (no main method), generate a Main.java
        that demonstrates all converted functions and can be run directly.
        Also writes a compile-and-run script.
        """
        lang = self.analysis.source_language
        if lang != "java":
            return

        # Check if source already has a main method
        if "public static void main" in self.source_code:
            return  # already has entry point, nothing to add

        src_file = self.source_file.stem  # e.g. "FinancialCalculator"
        package  = ""
        for line in self.source_code.splitlines():
            if line.strip().startswith("package "):
                package = line.strip().rstrip(";").replace("package ", "")
                break

        # Build demo calls for each non-kept function
        demo_calls = []
        for fn in self.analysis.functions:
            if fn.recommended_language == "keep" or fn.is_orchestrator:
                continue
            demo_calls.append(
                f'        System.out.println("  {fn.name}() — {fn.recommended_language} '
                f'via GraalVM Sulong (~{fn.energy_savings_percent:.0f}% energy saving)");'
            )

        import_stmt = f"import {package}.{src_file};" if package else ""

        # Build actual invocations per function pattern
        invocations = []
        for fn in self.analysis.functions:
            if fn.recommended_language == "keep" or fn.is_orchestrator:
                continue
            inv = self._generate_demo_invocation(fn, src_file)
            if inv:
                invocations.extend(inv)

        main_java = (
            f"// Auto-generated by GraalVM Optimizer — demo entry point\n"
            f"{import_stmt}\n"
            f"import java.util.Arrays;\n"
            f"\n"
            f"public class Main {{\n"
            f"    public static void main(String[] args) throws Exception {{\n"
            f'        System.out.println("GraalVM Polyglot Optimizer -- {src_file} Demo");\n'
            f'        System.out.println("Running all converted functions via GraalVM Sulong...\\n");\n'
            + "\n".join(invocations) + "\n"
            f'        System.out.println("\\nDone. Replace this demo with your own main class.");\n'
            f"    }}\n"
            f"}}\n"
        )

        (self.output_dir / "Main.java").write_text(main_java, encoding='utf-8')

        # Also write a compile.sh that sets up the package structure correctly
        pkg_path = package.replace(".", "/") if package else ""
        compile_sh = (
            "#!/bin/bash\n"
            'DIR="$(cd "$(dirname "$0")" && pwd)"\n'
            "mkdir -p \"$DIR/out\"\n"
        )
        if pkg_path:
            compile_sh += (
                f'mkdir -p "$DIR/out/{pkg_path}"\n'
                f'cp "$DIR/{src_file}.java" "$DIR/out/{pkg_path}/"\n'
                f'javac -encoding UTF-8 -cp "$GRAALVM_HOME/lib/graalvm/graal-sdk.jar" -d "$DIR/out" "$DIR/out/{pkg_path}/{src_file}.java" "$DIR/Main.java"\n'
            )
        else:
            compile_sh += f'javac -encoding UTF-8 -cp "$GRAALVM_HOME/lib/graalvm/graal-sdk.jar" -d "$DIR/out" "$DIR/{src_file}.java" "$DIR/Main.java"\n'

        compile_sh += 'echo "✅ Compiled to out/"\n'
        p = self.output_dir / "compile.sh"
        p.write_text(compile_sh, encoding='utf-8')
        p.chmod(0o755)


    def _write_test_suite(self, native_groups: dict):
        """Generate TestSuite.java using a static template — avoids string escaping hell."""
        lang = self.analysis.source_language
        if lang != "java":
            return

        src_file = self.source_file.stem
        package  = ""
        for line in self.source_code.splitlines():
            if line.strip().startswith("package "):
                package = line.strip().rstrip(";").replace("package ", "")
                break

        import_stmt = "import " + package + "." + src_file + ";" if package else ""

        # Build test cases per function
        test_lines = []
        for fn in self.analysis.functions:
            if fn.recommended_language == "keep" or fn.is_orchestrator:
                continue
            tc = self._generate_test_case(fn)
            test_lines.extend(tc)

        if not test_lines:
            return

        # Load template
        template_path = Path(__file__).parent / "TestSuite.java.template"
        if not template_path.exists():
            return
        template = template_path.read_text(encoding='utf-8')
        # Strip BOM and any leading whitespace/dots from Windows line endings
        template = template.lstrip('\ufeff').lstrip('.').lstrip()

        java = template.replace("%%IMPORTS%%", import_stmt)
        java = java.replace("%%TEST_CASES%%", "\n".join(test_lines))

        (self.output_dir / "TestSuite.java").write_text(java, encoding='utf-8')


    def _write_benchmark_suite(self):
        """Generate BenchmarkSuite.java — runs each optimized function WARMUP+MEASURE times
        on both the Java-only path and the native path, prints JSON results to stdout.
        Designed to be run via: docker run --rm <image> java -cp /app/out ... BenchmarkSuite
        """
        lang = self.analysis.source_language
        if lang != "java":
            return

        fns = [f for f in self.analysis.functions
               if f.recommended_language != "keep" and not f.is_orchestrator]
        if not fns:
            return

        src_file = self.source_file.stem
        package  = ""
        for line in self.source_code.splitlines():
            if line.strip().startswith("package "):
                package = line.strip().rstrip(";").replace("package ", "")
                break

        import_stmt = f"import {package}.{src_file};" if package else ""

        bench_cases = []
        for fn in fns:
            bench_cases.extend(self._generate_benchmark_case(fn))

        java = f"""// Auto-generated by GraalVM Optimizer — benchmark suite
// Launched twice by the optimizer API:
//   Pass 1 (java):   java -cp /app/out -Dnative.disabled=true  -Dnative.dir=/app/native BenchmarkSuite java
//   Pass 2 (native): java -cp /app/out -Dnative.disabled=false -Dnative.dir=/app/native BenchmarkSuite native
// Each pass prints a JSON array of {{function, mode, meanMs, p95Ms}} to stdout.
{import_stmt}
import java.util.Arrays;
import java.util.Random;

public class BenchmarkSuite {{
    static final int WARMUP  = 5;
    static final int MEASURE = 100;

    public static void main(String[] args) throws Exception {{
        String mode = (args.length > 0) ? args[0] : "native";
        // Diagnostic: log native context state to stderr so it doesn't pollute JSON stdout
        boolean nativeDisabled = "true".equalsIgnoreCase(System.getProperty("native.disabled", "false"));
        String nativeDir = System.getProperty("native.dir", System.getProperty("user.dir") + "/native");
        java.io.File nativeDirF = new java.io.File(nativeDir);
        String[] bcFiles = nativeDirF.list((d,n) -> n.endsWith(".bc"));
        System.err.println("[BenchmarkSuite] mode=" + mode
            + " native.disabled=" + nativeDisabled
            + " native.dir=" + nativeDir
            + " dir.exists=" + nativeDirF.exists()
            + " bc-files=" + java.util.Arrays.toString(bcFiles));
        System.out.println("[");
        boolean first = true;
{chr(10).join(bench_cases)}
        System.out.println("]");
    }}

    static long[] measure(Runnable fn, int n) {{
        long[] t = new long[n];
        for (int i = 0; i < n; i++) {{
            long s = System.nanoTime(); fn.run(); t[i] = System.nanoTime() - s;
        }}
        return t;
    }}

    static double mean(long[] t) {{
        double s = 0; for (long v : t) s += v; return s / t.length;
    }}

    static double p95ms(long[] t) {{
        long[] s = Arrays.copyOf(t, t.length); Arrays.sort(s);
        return s[(int)(s.length * 0.95)] / 1e6;
    }}

    static void printResult(boolean first, String name, String lang, long[] times) {{
        if (!first) System.out.println(",");
        String mode = System.getProperty("native.disabled", "false").equals("true") ? "java" : "native";
        System.out.printf(
            "  {{%n" +
            "    \\"function\\": \\"%s\\",%n" +
            "    \\"targetLanguage\\": \\"%s\\",%n" +
            "    \\"mode\\": \\"%s\\",%n" +
            "    \\"meanMs\\": %.4f,%n" +
            "    \\"p95Ms\\": %.4f%n" +
            "  }}",
            name, lang, mode, mean(times) / 1e6, p95ms(times)
        );
    }}
}}
"""
        (self.output_dir / "BenchmarkSuite.java").write_text(java, encoding='utf-8')


    def _generate_benchmark_case(self, fn) -> list:
        """Generate benchmark warmup+measure block for one function, returns Java source lines."""
        name   = fn.name
        cat    = fn.category.lower() if fn.category else ""
        src    = self.source_file.stem
        lang   = fn.recommended_language
        indent = "        "

        # Input setup — right-sized to ensure computation dominates interop overhead
        if any(k in name.lower() or k in cat for k in ["sort", "sorting"]):
            setup = [
                f"{indent}// --- {name} ---",
                f"{indent}double[] _bIn_{name} = new double[500];",
                f"{indent}{{ Random _r = new Random(42); for (int i=0;i<500;i++) _bIn_{name}[i]=_r.nextDouble()*10000; }}",
            ]
            java_call   = f"{src}.{name}(_bIn_{name}.clone())"
            native_call = f"{src}.{name}(_bIn_{name}.clone())"
        elif any(k in name.lower() or k in cat for k in ["monte", "carlo", "simulation"]):
            setup = [f"{indent}// --- {name} ---"]
            java_call   = f"{src}.{name}(10_000_000.0, 0.07, 0.20, 100_000, 252)"
            native_call = f"{src}.{name}(10_000_000.0, 0.07, 0.20, 100_000, 252)"
        elif any(k in name.lower() or k in cat for k in ["amort", "mortgage", "loan"]):
            setup = [f"{indent}// --- {name} ---"]
            java_call   = f"{src}.{name}(250_000.0, 6.75, 360)"
            native_call = f"{src}.{name}(250_000.0, 6.75, 360)"
        elif any(k in name.lower() or k in cat for k in ["fraud", "anomaly", "pattern"]):
            setup = [
                f"{indent}// --- {name} ---",
                f"{indent}double[] _bAmt_{name} = new double[500]; long[] _bTs_{name} = new long[500]; String[] _bLoc_{name} = new String[500];",
                f"{indent}{{ Random _r=new Random(42); String[] locs={{\"NY\",\"NJ\",\"CA\",\"TX\",\"ONLINE\"}};",
                f"{indent}  for(int i=0;i<500;i++){{ _bAmt_{name}[i]=50+_r.nextDouble()*500; _bTs_{name}[i]=System.currentTimeMillis()-_r.nextInt(3600000); _bLoc_{name}[i]=locs[_r.nextInt(5)]; }} }}",
            ]
            java_call   = f"{src}.{name}(_bAmt_{name}, _bTs_{name}, _bLoc_{name})"
            native_call = f"{src}.{name}(_bAmt_{name}, _bTs_{name}, _bLoc_{name})"
        elif any(k in name.lower() or k in cat for k in ["risk", "score", "recursive", "weight"]):
            setup = [
                f"{indent}// --- {name} ---",
                f"{indent}double[] _bF_{name} = new double[16]; double[] _bW_{name} = new double[16];",
                f"{indent}{{ Random _r=new Random(42); double s=0; for(int i=0;i<16;i++){{ _bF_{name}[i]=_r.nextDouble(); _bW_{name}[i]=_r.nextDouble(); s+=_bW_{name}[i]; }}",
                f"{indent}  for(int i=0;i<16;i++) _bW_{name}[i]/=s; }}",
            ]
            java_call   = f"{src}.{name}(_bF_{name}, _bW_{name}, 4)"
            native_call = f"{src}.{name}(_bF_{name}, _bW_{name}, 4)"
        else:
            return [f"{indent}// SKIP {name} — no benchmark pattern matched"]

        # BenchmarkSuite is launched twice by the API:
        #   Pass 1: -Dnative.disabled=true  → measures Java path, prints json with mode=java
        #   Pass 2: (default)               → measures native path, prints json with mode=native
        # The mode is passed as args[0] to main().
        lines = setup + [
            f"{indent}for (int _w=0; _w<WARMUP; _w++) {java_call};",
            f"{indent}long[] _t_{name} = measure(() -> {java_call}, MEASURE);",
            f"{indent}printResult(first, \"{name}\", \"{lang}\", _t_{name});",
            f"{indent}first = false;",
            "",
        ]
        return lines

    def _generate_test_case(self, fn) -> list:
        name = fn.name
        cat  = fn.category.lower() if fn.category else ""
        src  = self.source_file.stem
        sep  = '        System.out.println("--- ' + name + ' ---");'

        if any(k in name.lower() or k in cat for k in ["sort", "sorting"]):
            return [
                sep,
                '        double[] _in = {9.0, 3.0, 7.0, 1.0, 5.0, 8.0, 2.0, 6.0, 4.0, 0.0};',
                '        double[] _ja = ' + src + '.' + name + '(_in.clone());',
                '        double[] _na = ' + src + '.' + name + '(_in.clone());',
                '        checkArray("' + name + '", _ja, _na, STRICT_TOL);',
                "",
            ]
        if any(k in name.lower() or k in cat for k in ["monte", "carlo", "simulation"]):
            return [
                sep,
                '        var _jm = ' + src + '.' + name + '(100_000.0, 0.07, 0.20, 10_000, 252);',
                '        var _nm = ' + src + '.' + name + '(100_000.0, 0.07, 0.20, 10_000, 252);',
                '        check("' + name + '.var95", _jm.var95(),     _nm.var95(),     LOOSE_TOL);',
                '        check("' + name + '.mean",  _jm.meanValue(), _nm.meanValue(), LOOSE_TOL);',
                "",
            ]
        if any(k in name.lower() or k in cat for k in ["amort", "mortgage", "loan"]):
            return [
                sep,
                '        var _ja2 = ' + src + '.' + name + '(250_000.0, 6.75, 360);',
                '        var _na2 = ' + src + '.' + name + '(250_000.0, 6.75, 360);',
                '        check("' + name + '.payment", _ja2.get(0).payment(),   _na2.get(0).payment(),   STRICT_TOL);',
                '        check("' + name + '.balance", _ja2.get(359).balance(), _na2.get(359).balance(), STRICT_TOL);',
                "",
            ]
        if any(k in name.lower() or k in cat for k in ["fraud", "anomaly", "pattern"]):
            return [
                sep,
                '        double[] _fa = {100,200,300,400,500};',
                '        long[]   _ft = {100000L,200000L,300000L,400000L,500000L};',
                '        String[] _fl = {"NY","CA","TX","FL","WA"};',
                '        var _jf = ' + src + '.' + name + '(_fa, _ft, _fl);',
                '        var _nf = ' + src + '.' + name + '(_fa, _ft, _fl);',
                '        check("' + name + '.riskScore", _jf.riskScore(), _nf.riskScore(), STRICT_TOL);',
                '        check("' + name + '.flagCount", (double)_jf.flagCount(), (double)_nf.flagCount(), STRICT_TOL);',
                "",
            ]
        if any(k in name.lower() or k in cat for k in ["risk", "score", "recursive", "weight"]):
            return [
                sep,
                '        double[] _rf = {0.35, 0.30, 0.15, 0.10, 0.10};',
                '        double[] _rw = {0.40, 0.30, 0.10, 0.10, 0.10};',
                '        double _jr = ' + src + '.' + name + '(_rf, _rw, 3);',
                '        double _nr = ' + src + '.' + name + '(_rf, _rw, 3);',
                '        check("' + name + '", _jr, _nr, STRICT_TOL);',
                "",
            ]
        return [
            sep,
            '        System.out.println("  SKIP ' + name + ' - no pattern test available");',
            "",
        ]

    def _generate_demo_invocation(self, fn, src_file: str) -> list:
        """Generate actual Java invocation code for a function to prove C path works."""
        name     = fn.name
        category = fn.category.lower() if fn.category else ""
        lines    = [f'        System.out.println("--- {name}() ---");']

        if any(k in name.lower() or k in category for k in ["sort", "sorting"]):
            lines += [
                f'        double[] _{name}_in = {{9.0, 3.0, 7.0, 1.0, 5.0, 8.0, 2.0, 6.0, 4.0, 0.0}};',
                f'        double[] _{name}_out = {src_file}.{name}(_{name}_in);',
                f'        System.out.println("  result: " + Arrays.toString(_{name}_out));',
            ]
        elif any(k in name.lower() or k in category for k in ["monte", "carlo", "simulation"]):
            lines += [
                f'        var _{name}_r = {src_file}.{name}(100_000.0, 0.07, 0.20, 10_000, 252);',
                f'        System.out.printf("  VaR95=$%.2f  mean=$%.2f%n", _{name}_r.var95(), _{name}_r.meanValue());',
            ]
        elif any(k in name.lower() or k in category for k in ["amort", "mortgage", "loan"]):
            lines += [
                f'        var _{name}_s = {src_file}.{name}(250_000.0, 6.75, 360);',
                f'        System.out.printf("  payment=$%.2f  final_balance=$%.2f%n",',
                f'            _{name}_s.get(0).payment(), _{name}_s.get(359).balance());',
            ]
        elif any(k in name.lower() or k in category for k in ["fraud", "anomaly", "pattern"]):
            lines += [
                f'        double[] _{name}_a = {{100,200,300,400,500}};',
                f'        long[]   _{name}_t = {{100000L,200000L,300000L,400000L,500000L}};',
                f'        String[] _{name}_l = {{"NY","CA","TX","FL","WA"}};',
                f'        var _{name}_f = {src_file}.{name}(_{name}_a, _{name}_t, _{name}_l);',
                f'        System.out.printf("  riskScore=%.2f  flags=%s%n", _{name}_f.riskScore(), _{name}_f.flags());',
            ]
        elif any(k in name.lower() or k in category for k in ["risk", "score", "weight"]):
            lines += [
                f'        double[] _{name}_f = {{0.35,0.30,0.15,0.10,0.10}};',
                f'        double[] _{name}_w = {{0.40,0.30,0.10,0.10,0.10}};',
                f'        double _{name}_r = {src_file}.{name}(_{name}_f, _{name}_w, 3);',
                f'        System.out.printf("  score=%.6f%n", _{name}_r);',
            ]
        else:
            lines += [f'        System.out.println("  (no demo available for this pattern)");']

        lines.append('        System.out.println();')
        return lines

    def _write_native_file(self, lang: str, fns: list) -> Path:
        lang_info = TARGET_LANGUAGES.get(lang, {})
        ext  = lang_info.get("ext", ".c")
        stem = f"native_{lang.lower().replace('+', 'p').replace(' ', '_')}"
        out_path = self.native_dir / (stem + ext)
        if lang in ("C", "C++"):
            content = self._build_c_file(lang, fns, stem + ext)
        elif lang == "JavaScript":
            content = self._build_js_file(fns, stem + ext)
        elif lang == "Rust":
            content = self._build_rust_file(fns, stem + ext)
        else:
            content = "\n".join(fn.rewritten_code for fn in fns)
        out_path.write_text(content, encoding='utf-8')
        return out_path

    def _build_c_file(self, lang: str, fns: list, filename: str) -> str:
        # Filter out any functions whose rewritten code is actually Rust
        # (can happen when CodeBERT overrides language after Claude wrote Rust)
        c_fns = [fn for fn in fns
                 if not any(marker in fn.rewritten_code
                            for marker in ('use std::', '#[no_mangle]', 'pub extern', 'pub fn '))]
        if not c_fns:
            return f"// {filename} — no valid {lang} functions\n"
        all_code = "\n\n".join(fn.rewritten_code for fn in c_fns)
        needs_header = "#include" not in all_code
        header = C_FILE_HEADER.format(
            filename=filename,
            target_lang=lang,
            reason=c_fns[0].reason if c_fns else "",
            savings=int(c_fns[0].energy_savings_percent) if c_fns else 0,
            compile_cmd=f"clang -O2 -emit-llvm -c {filename} -o {filename.replace('.c','.bc')} --target=x86_64-unknown-linux-gnu",
        )
        std_headers = "#include <stdio.h>\n#include <stdlib.h>\n#include <math.h>\n#include <string.h>\n\n"
        if needs_header:
            combined = header + std_headers + all_code
        else:
            combined = header + all_code

        # Fix common Claude code generation issues in combined file
        combined = self._fix_common_c_issues(combined)
        return combined

    def _fix_common_c_issues(self, code: str) -> str:
        """Fix known patterns of Claude-generated C code issues."""
        import re

        # Fix: abs() on long values — should be labs()
        code = re.sub(r'\babs\(([^)]*timestamps[^)]*|[^)]*time[^)]*|[^)]*long[^)]*)\)',
                      lambda m: 'labs(' + m.group(1) + ')', code)

        # Fix: volatility used outside its scope in gaussian functions
        # Replace "mag = volatility * sqrt" with "mag = sqrt"
        # The vol parameter is passed to the outer function, not to nextGaussian
        code = code.replace(
            'double mag = volatility * sqrt(-2.0 * log(u));',
            'double mag = sqrt(-2.0 * log(u));'
        )
        code = code.replace(
            'double mag = volatility * sqrt(-2.0f * logf(u));',
            'double mag = sqrt(-2.0f * logf(u));'
        )

        # Fix: string.h missing when strcmp/strcpy used
        if ('strcmp(' in code or 'strcpy(' in code or 'strlen(' in code) and \
           '#include <string.h>' not in code:
            code = '#include <string.h>\n' + code

        # Fix: math.h missing when sqrt/log/exp/pow used
        if any(f in code for f in ['sqrt(', 'log(', 'exp(', 'pow(', 'fmod(']) and \
           '#include <math.h>' not in code:
            code = '#include <math.h>\n' + code

        # Fix: ULONG_MAX requires <limits.h>
        if 'ULONG_MAX' in code and '#include <limits.h>' not in code:
            code = '#include <limits.h>\n' + code

        # Fix: UINT64_MAX, INT64_MAX etc require <stdint.h>
        if any(m in code for m in ['UINT64_MAX', 'INT64_MAX', 'UINT32_MAX', 'uint64_t', 'int64_t']) and \
           '#include <stdint.h>' not in code:
            code = '#include <stdint.h>\n' + code

        # Fix: NULL / labs() / llabs() not defined without <stdlib.h>
        if any(s in code for s in ['NULL', 'labs(', 'llabs(', 'malloc(', 'free(', 'qsort(']) \
                and '#include <stdlib.h>' not in code:
            code = '#include <stdlib.h>\n' + code

        # Fix: Box-Muller duplicate statics — normalize to single declaration
        # Claude sometimes generates "static double z1;" separately then "static double z0, z1;"
        for old_pat, new_pat in [
            ('static double z1;\n    static double z0, z1;', 'static double z0 = 0.0, z1 = 0.0;'),
            ('static double z1;\n        static double z0, z1;', 'static double z0 = 0.0, z1 = 0.0;'),
            ('static double spare;\n    static double z0, z1;', 'static double spare = 0.0, z0 = 0.0, z1 = 0.0;'),
            ('static double spare;\n        static double z0, z1;', 'static double spare = 0.0, z0 = 0.0, z1 = 0.0;'),
        ]:
            code = code.replace(old_pat, new_pat)

        return code

    def _build_js_file(self, fns: list, filename: str) -> str:
        header = JS_FILE_HEADER.format(
            filename=filename,
            reason=fns[0].reason if fns else "",
            savings=int(fns[0].energy_savings_percent) if fns else 0,
        )
        all_code = "\n\n".join(fn.rewritten_code for fn in fns)
        exports = "\n// GraalVM polyglot exports\n"
        for fn in fns:
            exports += f"Polyglot.export('{fn.name}', {fn.name});\n"
        return header + all_code + exports


    def _build_rust_file(self, fns: list, filename: str) -> str:
        """Generate a Rust file with #[no_mangle] pub extern "C" exports."""
        header = RUST_FILE_HEADER.format(
            filename=filename,
            reason=fns[0].reason if fns else "",
            savings=int(fns[0].energy_savings_percent) if fns else 0,
        )

        # Collect all use/extern declarations from all functions, deduplicate
        # then strip them from the individual function bodies so they appear once at top
        use_lines = set()
        cleaned_parts = []
        for fn in fns:
            code = fn.rewritten_code
            body_lines = []
            for line in code.splitlines():
                stripped = line.strip()
                if stripped.startswith("use ") or stripped.startswith("extern crate "):
                    use_lines.add(stripped)
                elif stripped.startswith("#!["):
                    # crate-level attributes — hoist to top, don't repeat
                    use_lines.add(stripped)
                else:
                    body_lines.append(line)
            code = "\n".join(body_lines).strip()
            # Ensure function is exported correctly
            if "pub extern" not in code and "pub fn" not in code:
                code = '#[no_mangle]\npub extern "C" ' + code.lstrip("pub ")
            elif "#[no_mangle]" not in code:
                code = '#[no_mangle]\n' + code
            cleaned_parts.append(code)

        # Build preamble: crate attrs first, then use statements
        crate_attrs = sorted(l for l in use_lines if l.startswith("#!["))
        use_stmts   = sorted(l for l in use_lines if not l.startswith("#!["))
        preamble = "\n".join(crate_attrs + use_stmts)
        if preamble:
            preamble += "\n\n"

        return header + preamble + "\n\n".join(cleaned_parts)

    def _build_step(self, lang: str, src_path: Path) -> dict:
        stem = src_path.stem
        if lang == "C":
            return {
                "lang": "C", "src": str(src_path),
                "bc":  str(self.native_dir / (stem + ".bc")),
                "so":  str(self.native_dir / (stem + ".so")),
            }
        elif lang == "C++":
            return {
                "lang": "C++", "src": str(src_path),
                "bc":  str(self.native_dir / (stem + ".bc")),
                "so":  str(self.native_dir / (stem + ".so")),
            }
        return {"lang": lang, "src": str(src_path)}

    def _write_orchestrator(self, native_groups: dict) -> Path:
        lang = self.analysis.source_language
        ext = SUPPORTED_LANGUAGES.get(lang, {}).get("ext", ".py")
        out_path = self.output_dir / self.source_file.name

        header = POLYGLOT_HEADERS.get(lang, "")
        modified = self._inject_polyglot_calls(self.source_code, native_groups, lang)

        if lang == "java":
            # Java: imports must come before ALL class declarations.
            # Extract imports from original source, put them first,
            # then polyglot header (which adds _GraalContext class),
            # then the rest of the original code (without its imports).
            import_lines = []
            non_import_lines = []
            for line in self.source_code.splitlines():
                stripped = line.strip()
                if stripped.startswith("import ") or stripped.startswith("package "):
                    import_lines.append(line)
                else:
                    non_import_lines.append(line)

            # Rebuild: original imports + polyglot header imports/class + modified body
            imports_block = "\n".join(import_lines) + "\n\n" if import_lines else ""
            body = self._inject_polyglot_calls(
                "\n".join(non_import_lines), native_groups, lang)
            out_path.write_text(imports_block + header + body, encoding='utf-8')
        else:
            out_path.write_text(header + modified, encoding='utf-8')

        return out_path

    def _inject_polyglot_calls(self, source: str, native_groups: dict, lang: str) -> str:
        """
        Injects polyglot loader calls and replaces function bodies
        that have been moved to native code with polyglot dispatch calls.
        """
        lines = source.splitlines()
        result_lines = []

        # Build a map of function name -> target lang
        fn_map = {}
        for fn in self.analysis.functions:
            if fn.recommended_language != "keep" and not fn.is_orchestrator:
                fn_map[fn.name] = fn

        # Inject loader calls at module level (after imports)
        loaders_injected = False

        if lang == "python":
            result_lines.append("# ── Native module loaders (auto-generated) ──────────────────────────")
            for target_lang, fns in native_groups.items():
                stem = f"native_{target_lang.lower().replace('+', 'p').replace(' ', '_')}"
                if target_lang in ("C", "C++"):
                    result_lines.append(f"_lib_{stem} = _load_native('{stem}')")
                elif target_lang == "JavaScript":
                    result_lines.append(f"_lib_{stem} = _load_js('{stem}')")
            result_lines.append("")

            # Now rewrite function definitions to be polyglot stubs
            i = 0
            while i < len(lines):
                line = lines[i]
                fn_found = None
                for fn_name, fn in fn_map.items():
                    if re.match(rf'\s*def {re.escape(fn_name)}\s*\(', line):
                        fn_found = fn
                        break

                if fn_found:
                    # Extract the original function signature
                    sig_line = line
                    # Skip original body
                    indent = len(line) - len(line.lstrip())
                    j = i + 1
                    while j < len(lines):
                        next_line = lines[j]
                        if next_line.strip() == "":
                            j += 1
                            continue
                        next_indent = len(next_line) - len(next_line.lstrip())
                        if next_indent <= indent and next_line.strip():
                            break
                        j += 1

                    # Write polyglot stub
                    target_lang = fn_found.recommended_language
                    stem = f"native_{target_lang.lower().replace('+', 'p').replace(' ', '_')}"
                    params = re.search(r'\(([^)]*)\)', sig_line)
                    param_str = params.group(1) if params else ""
                    param_names = [p.strip().split(':')[0].strip()
                                   for p in param_str.split(',') if p.strip()]

                    result_lines.append(f"# [GraalVM → {target_lang}] {fn_found.reason}")
                    result_lines.append(sig_line)
                    result_lines.append(f"    return _lib_{stem}.{fn_found.name}({', '.join(param_names)})")
                    result_lines.append("")
                    i = j
                else:
                    result_lines.append(line)
                    i += 1

        elif lang == "java":
            # For Java: inject module loaders after class opening brace,
            # then replace each converted function's body with a _GraalContext dispatch call.
            loaders_injected = False
            i = 0
            while i < len(lines):
                line = lines[i]

                # Inject static loaders right after "public class Foo {" line
                if not loaders_injected and re.match(r'\s*public\s+class\s+', line) and '{' in line:
                    result_lines.append(line)
                    result_lines.append("")
                    result_lines.append("    // ── GraalVM native module handles (auto-generated) ──────────────")
                    for target_lang_key, fns_list in native_groups.items():
                        stem = f"native_{target_lang_key.lower().replace('+', 'p').replace(' ', '_')}"
                        result_lines.append(f"    static final org.graalvm.polyglot.Value _lib_{stem} = _GraalContext.loadLLVM(\"{stem}\");")
                    result_lines.append("")
                    loaders_injected = True
                    i += 1
                    continue

                # Check if this line is a method signature for a converted function
                fn_found = None
                for fn_name, fn in fn_map.items():
                    # Match: public static <type> functionName( or private <type> functionName(
                    if re.search(rf'\b{re.escape(fn_name)}\s*\(', line) and \
                       ('public' in line or 'private' in line or 'protected' in line) and \
                       '{' in line:
                        fn_found = fn
                        break

                if fn_found:
                    # Write the original method signature line
                    result_lines.append(line)

                    # Skip the original method body — find matching closing brace
                    brace_depth = line.count('{') - line.count('}')
                    j = i + 1
                    while j < len(lines) and brace_depth > 0:
                        brace_depth += lines[j].count('{') - lines[j].count('}')
                        j += 1

                    # Extract parameter names from the signature
                    params_match = re.search(r'\(([^)]*)\)', line)
                    param_str = params_match.group(1) if params_match else ""
                    # Parse Java params: "double[] amounts, int n" → ["amounts", "n"]
                    param_names = []
                    for param in param_str.split(','):
                        param = param.strip()
                        if param:
                            # Take the last token (variable name), strip array brackets
                            parts = param.split()
                            if parts:
                                pname = parts[-1].replace('[]', '').strip()
                                if pname and not pname.startswith('//'):
                                    param_names.append(pname)

                    # Extract return type (including generics like Map<String, Integer>)
                    ret_match = re.search(
                        r'(?:public|private|protected|static)\s+(?:static\s+)?([\w<>, \[\]]+?)\s+' +
                        re.escape(fn_found.name) + r'\s*\(', line)
                    ret_type = ret_match.group(1).strip() if ret_match else "void"

                    # Get the module stem for this function
                    target_lang_val = fn_found.recommended_language
                    stem = f"native_{target_lang_val.lower().replace('+', 'p').replace(' ', '_')}"

                    # Build dispatch body
                    indent = "        "  # 8 spaces (inside method body)
                    result_lines.append(f"{indent}// [GraalVM -> {target_lang_val}] {fn_found.reason}")
                    result_lines.append(f"{indent}org.graalvm.polyglot.Value _lib = _GraalContext.loadLLVM(\"{stem}\");")
                    result_lines.append(f"{indent}if (_lib != null) {{")

                    # GraalVM Sulong cannot read Java heap arrays as C pointers.
                    # Convert every array param to a DirectByteBuffer (native memory) first.
                    # C signature: fn(double* arr, int length, ...) needs buf, arr.length, ...
                    expanded_args = []
                    for pname in param_names:
                        arr_match = re.search(
                            r'(double|long|int|float)\s*\[\]\s+' + re.escape(pname) + r'[,)]',
                            line
                        )
                        if arr_match:
                            elem_type = arr_match.group(1)
                            bytes_per = {"double": "Double.BYTES", "long": "Long.BYTES",
                                         "int": "Integer.BYTES", "float": "Float.BYTES"}[elem_type]
                            buf_var = f"_buf_{pname}"
                            result_lines.append(f"{indent}    java.nio.ByteBuffer {buf_var} = java.nio.ByteBuffer"
                                                f".allocateDirect({pname}.length * {bytes_per})"
                                                f".order(java.nio.ByteOrder.nativeOrder());")
                            result_lines.append(f"{indent}    {buf_var}.as{elem_type.capitalize()}Buffer().put({pname}); {buf_var}.rewind();")
                            expanded_args.append(buf_var)
                            expanded_args.append(pname + ".length")
                        else:
                            expanded_args.append(pname)
                    args = ", ".join(expanded_args)
                    fn_var = f"_fn_{fn_found.name}"
                    result_lines.append(f"{indent}    org.graalvm.polyglot.Value {fn_var} = _lib.getMember(\"{fn_found.name}\");")
                    result_lines.append(f"{indent}    if ({fn_var} != null) {{")
                    is_array_return = "[]" in ret_type
                    is_map_return   = "Map" in ret_type or "List" in ret_type or "Set" in ret_type
                    if ret_type == "void":
                        result_lines.append(f"{indent}        {fn_var}.execute({args});")
                        result_lines.append(f"{indent}        return;")
                    elif ret_type == "double":
                        result_lines.append(f"{indent}        return {fn_var}.execute({args}).asDouble();")
                    elif ret_type in ("int", "long", "Integer", "Long"):
                        result_lines.append(f"{indent}        return (int) {fn_var}.execute({args}).asLong();")
                    elif ret_type in ("float", "Float"):
                        result_lines.append(f"{indent}        return (float) {fn_var}.execute({args}).asDouble();")
                    elif ret_type in ("boolean", "Boolean"):
                        result_lines.append(f"{indent}        return {fn_var}.execute({args}).asBoolean();")
                    elif is_array_return:
                        # Output buffer pattern: C writes sorted/computed result into a separate
                        # DirectByteBuffer (native memory). Java reads it back after the call.
                        base_type = ret_type.replace("[]", "").strip()
                        buf_type  = "DoubleBuffer" if base_type == "double" else "IntBuffer"
                        bytes_per = "Double.BYTES" if base_type == "double" else "Integer.BYTES"
                        size_expr = next(
                            (p + ".length" for p in param_names
                             if re.search(r'\w+\[\]\s+' + re.escape(p), line)),
                            "64"
                        )
                        out_buf_var = f"_outBuf_{fn_found.name}"
                        result_lines.append(f"{indent}        // Output DirectByteBuffer: native writes result here, Java reads back")
                        result_lines.append(f"{indent}        java.nio.ByteBuffer {out_buf_var} = java.nio.ByteBuffer"
                                            f".allocateDirect({size_expr} * {bytes_per})"
                                            f".order(java.nio.ByteOrder.nativeOrder());")
                        result_lines.append(f"{indent}        {fn_var}.execute({args}, {out_buf_var}, {size_expr});")
                        result_lines.append(f"{indent}        {ret_type} _out_{fn_found.name} = new {base_type}[{size_expr}];")
                        result_lines.append(f"{indent}        {out_buf_var}.rewind(); {out_buf_var}.as{buf_type}().get(_out_{fn_found.name});")
                        result_lines.append(f"{indent}        return _out_{fn_found.name};")
                    elif is_map_return:
                        # Flat array output buffer pattern (Option A): all logic in native,
                        # only 2 boundary crossings regardless of collection size.
                        # Infer value type from generics: Map<String,Integer>→int, Map<String,Double>→double
                        ret_upper = ret_type.upper()
                        if "DOUBLE" in ret_upper or "FLOAT" in ret_upper:
                            val_java_type, val_java_get = "double[]", ".asDouble()"
                        else:
                            val_java_type, val_java_get = "int[]", "(int) _ve.asLong()"
                        is_list_only = "List" in ret_type and "Map" not in ret_type

                        result_lines.append(f"{indent}        // Flat array output buffer: Java allocates, native fills, Java reconstructs")
                        result_lines.append(f"{indent}        int _maxEntries = 4096;")
                        result_lines.append(f"{indent}        int _keyStride  = 64;")

                        if is_list_only:
                            # List<Double> pattern: just a values buffer
                            result_lines.append(f"{indent}        {val_java_type} _valBuf = new {'double' if 'double' in val_java_type else 'int'}[_maxEntries];")
                            # Flatten any String[] params before the call
                            flat_args = _build_flat_args(param_names, line, result_lines, indent)
                            result_lines.append(f"{indent}        org.graalvm.polyglot.Value _fnVal = _lib.getMember(\"{fn_found.name}\");")
                            result_lines.append(f"{indent}        if (_fnVal != null) {{")
                            result_lines.append(f"{indent}            int _nEntries = (int) _fnVal.execute({flat_args}_valBuf, _maxEntries).asLong();")
                            result_lines.append(f"{indent}            java.util.List<{'Double' if 'double' in val_java_type else 'Integer'}> _res = new java.util.ArrayList<>(_nEntries);")
                            result_lines.append(f"{indent}            for (int _i = 0; _i < _nEntries; _i++) _res.add(_valBuf[_i]);")
                            result_lines.append(f"{indent}            return _res;")
                            result_lines.append(f"{indent}        }}")
                        else:
                            # Map<String,V> or Set<String> pattern: keys buffer + optional values buffer
                            result_lines.append(f"{indent}        byte[] _keyBuf = new byte[_maxEntries * _keyStride];")
                            result_lines.append(f"{indent}        {val_java_type} _valBuf = new {'double' if 'double' in val_java_type else 'int'}[_maxEntries];")
                            flat_args = _build_flat_args(param_names, line, result_lines, indent)
                            result_lines.append(f"{indent}        org.graalvm.polyglot.Value _fnVal = _lib.getMember(\"{fn_found.name}\");")
                            result_lines.append(f"{indent}        if (_fnVal != null) {{")
                            result_lines.append(f"{indent}            int _nEntries = (int) _fnVal.execute({flat_args}_keyBuf, _keyStride, _valBuf, _maxEntries).asLong();")
                            result_lines.append(f"{indent}            java.util.Map<String, {'Double' if 'double' in val_java_type else 'Integer'}> _res = new java.util.HashMap<>(_nEntries);")
                            result_lines.append(f"{indent}            for (int _i = 0; _i < _nEntries; _i++) {{")
                            result_lines.append(f"{indent}                String _k = new String(_keyBuf, _i * _keyStride, _keyStride, java.nio.charset.StandardCharsets.UTF_8).replace(\"\\0\", \"\").strip();")
                            result_lines.append(f"{indent}                _res.put(_k, _valBuf[_i]);")
                            result_lines.append(f"{indent}            }}")
                            result_lines.append(f"{indent}            return _res;")
                            result_lines.append(f"{indent}        }}")
                    else:
                        result_lines.append(f"{indent}        // Complex return type {ret_type}: fall through to Java")
                    result_lines.append(f"{indent}    }}")

                    result_lines.append(f"{indent}}}")
                    result_lines.append(f"{indent}// Java fallback:")
                    result_lines.append("")

                    # Now emit the original body lines
                    for body_line in lines[i+1:j]:
                        result_lines.append(body_line)

                    i = j
                else:
                    result_lines.append(line)
                    i += 1


        elif lang in ("javascript", "nodejs"):
            result_lines.append("// ── Native module loaders (auto-generated) ──────────────────────")
            for target_lang, fns in native_groups.items():
                stem = f"native_{target_lang.lower().replace('+', 'p').replace(' ', '_')}"
                if target_lang in ("C", "C++"):
                    result_lines.append(f"const _lib_{stem} = loadNative('{stem}');")
                elif target_lang == "JavaScript":
                    result_lines.append(f"const _lib_{stem} = loadJS('{stem}');")
            result_lines.append("")
            result_lines.extend(lines)

        else:
            result_lines.extend(lines)

        return "\n".join(result_lines)

    def _write_build_script(self, manifest: dict):
        lines = [
            "#!/bin/bash",
            "# Auto-generated build script — GraalVM Optimizer",
            f"# Compiles native modules for: {self.source_file.name}",
            "",
            "# Always work relative to this script's location",
            'DIR="$(cd "$(dirname "$0")" && pwd)"',
            'NATIVE_DIR="$DIR/native"',
            "",
            "# Detect compilers",
            'CLANG="${CLANG:-clang}"',
            'CLANGPP="${CLANGPP:-clang++}"',
            'RUSTC="${RUSTC:-rustc}"',
            "",
        ]

        for step in manifest["build_steps"]:
            lang = step.get("lang", "")
            src  = step.get("src", "")
            if lang in ("C", "C++"):
                stem     = Path(src).stem
                src_rel  = f'"$NATIVE_DIR/{Path(src).name}"'
                bc_out   = f'"$NATIVE_DIR/{stem}.bc"'
                compiler = '"$CLANG"' if lang == "C" else '"$CLANGPP"'
                lines += [
                    f"echo 'Compiling {lang}: {Path(src).name}'",
                    f"if {compiler} -O2 -emit-llvm -c {src_rel} -o {bc_out} "
                    f"--target=x86_64-unknown-linux-gnu 2>&1; then",
                    f"    echo '  OK {stem}.bc'",
                    "else",
                    f"    echo '  FAIL: {Path(src).name}'",
                    "fi",
                    "",
                ]
            elif lang == "Rust":
                stem    = Path(src).stem
                src_rel = f'"$NATIVE_DIR/{Path(src).name}"'
                bc_out  = f'"$NATIVE_DIR/{stem}.bc"'
                lines += [
                    f"echo 'Compiling Rust: {Path(src).name}'",
                    f'if "$RUSTC" --emit=llvm-bc -O --crate-type=cdylib {src_rel} -o {bc_out} 2>&1; then',
                    f"    echo '  OK {stem}.bc'",
                    "else",
                    f"    echo '  FAIL: {Path(src).name} (is rustc installed?)'",
                    "fi",
                    "",
                ]

        lines += [
            'echo ""',
            "echo '✅ Build complete'",
            'echo "Bitcode files:"',
            'ls -lh "$NATIVE_DIR"/*.bc 2>/dev/null || echo "  (none — check compiler errors above)"',
        ]

        build_sh = self.output_dir / "build.sh"
        build_sh.write_text("\n".join(lines), encoding='utf-8')
        build_sh.chmod(0o755)

    def _write_run_script(self, manifest: dict) -> Path:
        lang = self.analysis.source_language
        src_file = self.source_file.name
        lang_info = SUPPORTED_LANGUAGES.get(lang, {})
        runner = lang_info.get("runner", "python3")

        lines = [
            "#!/bin/bash",
            "# Auto-generated run script -- GraalVM Optimizer",
            f"# Usage: ./run.sh [args...]  (same as original: {runner} {src_file} [args...])",
            "",
            'DIR="$(cd "$(dirname "$0")" && pwd)"',
            'NATIVE_DIR="$DIR/native"',
            "",
            "# Bitcode files are baked into the Docker image during build.",
            "# If missing, the app runs with Java fallback automatically.",
            'if ! ls "$NATIVE_DIR"/*.bc 2>/dev/null | grep -q .; then',
            '    echo "WARNING: No bitcode files in $NATIVE_DIR -- running with Java fallback"',
            "fi",
            "",
        ]

        if lang == "java":
            lines += [
                "# Java — compile then run with GraalVM",
                'if command -v java &> /dev/null; then',
                '    echo "⚡ Compiling Java..."',
                '    bash "$DIR/compile.sh"',
                '    echo "⚡ Running with GraalVM java"',
                '    java \\',
                '        -cp "$DIR/out" \\',
                '        -Dpolyglot.engine.WarnInterpreterOnly=false \\',
                '        -Dpolyglot.llvm.verifyBitcode=false \\',
                '        -Dnative.dir="$NATIVE_DIR" \\',
                '        Main "$@"',
                "else",
                "    echo '✗ java not found — is GraalVM installed?'",
                "    exit 1",
                "fi",
            ]
        elif lang == "python":
            lines += [
                "if command -v graalpy &> /dev/null; then",
                "    echo '⚡ Running with GraalVM (graalpy)'",
                f'    graalpy "$DIR/{src_file}" "$@"',
                "else",
                f"    echo '⚠ graalpy not found — running with standard python3'",
                f'    python3 "$DIR/{src_file}" "$@"',
                "fi",
            ]
        elif lang in ("javascript", "nodejs"):
            lines += [
                "if command -v node &> /dev/null; then",
                "    echo '⚡ Running with GraalVM (node)'",
                f'    node "$DIR/{src_file}" "$@"',
                "else",
                "    echo '✗ node not found'",
                "    exit 1",
                "fi",
            ]
        else:
            lines += [
                f"echo '⚡ Running with {runner}'",
                f'{runner} "$DIR/{src_file}" "$@"',
            ]
        run_sh = self.output_dir / "run.sh"
        run_sh.write_text("\n".join(lines), encoding='utf-8')
        run_sh.chmod(0o755)
        return run_sh

    def _write_benchmark_sh(self):
        """Write benchmark.sh — launched by the API via docker run --rm <image> bash benchmark.sh.
        Runs BenchmarkSuite twice: once with native.disabled=true (Java path) and once without
        (native path). Prints two JSON arrays separated by a marker line the API can split on.
        """
        lang = self.analysis.source_language
        if lang != "java":
            return
        if not (self.output_dir / "BenchmarkSuite.java").exists():
            return

        cp = "/app/out:/opt/graalvm/lib/graalvm/graal-sdk.jar"
        jvm_flags = (
            "-Dpolyglot.engine.WarnInterpreterOnly=false "
            "-Dpolyglot.llvm.verifyBitcode=false "
            "-Dnative.dir=/app/native"
        )
        lines = [
            "#!/bin/bash",
            "# Auto-generated benchmark runner",
            "# Usage: docker run --rm <image> bash benchmark.sh",
            "",
            "echo '===JAVA_PASS==='",
            f"java -cp {cp} -Dnative.disabled=true {jvm_flags} BenchmarkSuite java",
            "echo '===NATIVE_PASS==='",
            f"java -cp {cp} -Dnative.disabled=false {jvm_flags} BenchmarkSuite native",
            "echo '===DONE==='",
        ]
        bench_sh = self.output_dir / "benchmark.sh"
        bench_sh.write_text("\n".join(lines), encoding='utf-8')
        bench_sh.chmod(0o755)

    def _write_dockerfile(self):
        lang = self.analysis.source_language
        src_file = self.source_file.stem  # stem only e.g. "FinancialCalculator" not "FinancialCalculator.java"
        src_name = self.source_file.name  # full name e.g. "FinancialCalculator.java"

        # Stage 1: compile C/C++ with clang (Ubuntu 22.04)
        # Stage 2: GraalVM CE 22.3.3 runtime — proven to work with gu install llvm
        pkg_path = package.replace(".", "/") if (hasattr(self, "_pkg") and self._pkg) else ""
        try:
            package_val = ""
            for line in self.source_code.splitlines():
                if line.strip().startswith("package "):
                    package_val = line.strip().rstrip(";").replace("package ", "")
                    break
            pkg_path = package_val.replace(".", "/") if package_val else ""
        except Exception:
            pkg_path = ""

        has_test_suite      = (self.output_dir / "TestSuite.java").exists()
        has_benchmark_suite = (self.output_dir / "BenchmarkSuite.java").exists()
        test_stage = ""
        if lang == "java" and has_test_suite:
            # Compile both TestSuite and BenchmarkSuite in the same stage
            bench_compile = (
                f'    javac -encoding UTF-8 -cp /opt/graalvm/lib/graalvm/graal-sdk.jar:/app/out '
                f'-d /app/out /app/BenchmarkSuite.java && \\\n'
            ) if has_benchmark_suite else ""

            if pkg_path:
                test_stage = (
                    '# Stage 3: compile and run test suite\n'
                    'FROM runtime AS tester\n'
                    f'RUN mkdir -p /app/out/{pkg_path} && \\\n'
                    f'    cp /app/{src_name} /app/out/{pkg_path}/{src_name} && \\\n'
                    f'    javac -encoding UTF-8 -cp /opt/graalvm/lib/graalvm/graal-sdk.jar -d /app/out /app/out/{pkg_path}/{src_name} /app/TestSuite.java && \\\n'
                    + bench_compile +
                    '    java -cp /app/out:/opt/graalvm/lib/graalvm/graal-sdk.jar \\\n'
                    '         -Dpolyglot.engine.WarnInterpreterOnly=false \\\n'
                    '         -Dpolyglot.llvm.verifyBitcode=false \\\n'
                    '         -Dnative.dir=/app/native \\\n'
                    '         TestSuite\n'
                    '\n'
                )
            else:
                test_stage = (
                    '# Stage 3: compile and run test suite\n'
                    'FROM runtime AS tester\n'
                    f'RUN javac -encoding UTF-8 -cp /opt/graalvm/lib/graalvm/graal-sdk.jar -d /app/out /app/{src_name} /app/TestSuite.java && \\\n'
                    + bench_compile +
                    '    java -cp /app/out:/opt/graalvm/lib/graalvm/graal-sdk.jar \\\n'
                    '         -Dpolyglot.engine.WarnInterpreterOnly=false \\\n'
                    '         -Dpolyglot.llvm.verifyBitcode=false \\\n'
                    '         -Dnative.dir=/app/native \\\n'
                    '         TestSuite\n'
                    '\n'
                )

        content = (
            '# ── GraalVM Polyglot Optimizer — Auto-generated Dockerfile ─────────────────\n'
            '# Stage 1: compile C/C++ to LLVM bitcode\n'
            'FROM ubuntu:22.04 AS builder\n'
            'RUN apt-get update -q && apt-get install -y -q clang && rm -rf /var/lib/apt/lists/*\n'
            'WORKDIR /build\n'
            'COPY native/ ./native/\n'
            'RUN for f in native/*.c; do \\\n'
            '        [ -f "$f" ] || continue; \\\n'
            '        name=$(basename "$f" .c); \\\n'
            '        clang -O2 -emit-llvm -c "$f" -o "native/$name.bc" \\\n'
            '        --target=x86_64-unknown-linux-gnu \\\n'
            '        && echo "OK $name.bc" || echo "FAIL $f"; \\\n'
            '    done\n'
            'RUN for f in native/*.cpp; do \\\n'
            '        [ -f "$f" ] || continue; \\\n'
            '        name=$(basename "$f" .cpp); \\\n'
            '        clang++ -O2 -emit-llvm -c "$f" -o "native/$name.bc" \\\n'
            '        --target=x86_64-unknown-linux-gnu \\\n'
            '        && echo "OK $name.bc" || echo "FAIL $f"; \\\n'
            '    done\n'
            '\n'
            '# Stage 2: GraalVM CE 22.3.3 runtime\n'
            'FROM ubuntu:20.04 AS runtime\n'
            'ENV DEBIAN_FRONTEND=noninteractive GRAALVM_HOME=/opt/graalvm\n'
            'RUN apt-get update -q && apt-get install -y -q curl tar && rm -rf /var/lib/apt/lists/*\n'
            'RUN curl -sL \\\n'
            '    https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.3/graalvm-ce-java17-linux-amd64-22.3.3.tar.gz \\\n'
            '    | tar -xz -C /opt && mv /opt/graalvm-ce-java17-22.3.3 /opt/graalvm\n'
            'ENV PATH="/opt/graalvm/bin:$PATH" JAVA_HOME="/opt/graalvm"\n'
            'RUN gu install llvm llvm-toolchain\n'
            'RUN mkdir -p /app/out\n'
            'WORKDIR /app\n'
            'COPY . .\n'
            'COPY --from=builder /build/native/*.bc ./native/\n'
            '\n'
        ) + test_stage + (
            f'# Stage 4: final image -- only reachable if Stage 3 tests passed\n'
            'FROM tester AS final\n'
            f'# Original command: java {src_name}\n'
            '# Run normally:    docker run <image>\n'
            '# Run benchmark:   docker run --rm <image> bash benchmark.sh\n'
            'ENTRYPOINT ["bash", "run.sh"]\n'
            'CMD []\n'
        ) if test_stage else (
            f'# Stage 3: final image\n'
            'FROM runtime AS final\n'
            f'# Original command: java {src_name}\n'
            '# Run benchmark:   docker run --rm <image> bash benchmark.sh\n'
            'ENTRYPOINT ["bash", "run.sh"]\n'
            'CMD []\n'
        )
        (self.output_dir / "Dockerfile").write_text(content, encoding='utf-8')

    def _write_docker_compose(self):
        src_file = self.source_file.name
        content = (
            'services:\n'
            '  graalvm-optimizer:\n'
            '    build:\n'
            '      context: .\n'
            '      dockerfile: Dockerfile\n'
            f'    container_name: graalvm-{src_file.replace(".", "-")}\n'
            '    stdin_open: true\n'
            '    tty: true\n'
            '    volumes:\n'
            '      - ./out:/app/out\n'
            '    environment:\n'
            '      - GRAAL_HOME=/usr/lib/graalvm\n'
        )
        (self.output_dir / "docker-compose.yml").write_text(content, encoding='utf-8')

    def _write_report(self, manifest: dict):
        fns = self.analysis.functions
        moved = [f for f in fns if f.recommended_language != "keep" and not f.is_orchestrator]
        kept = [f for f in fns if f.recommended_language == "keep" or f.is_orchestrator]
        avg_saving = sum(f.energy_savings_percent for f in moved) / len(moved) if moved else 0

        lines = [
            "# GraalVM Polyglot Optimization Report",
            f"**Source:** `{self.source_file.name}` ({self.analysis.source_language})",
            f"**Functions analyzed:** {len(fns)}",
            f"**Functions moved to native:** {len(moved)}",
            f"**Average energy saving:** ~{avg_saving:.0f}%",
            "",
            "## Function Breakdown",
            "",
            "| Function | Original | → Target | Saving | Reason |",
            "|---|---|---|---|---|",
        ]
        for fn in fns:
            target = fn.recommended_language if not fn.is_orchestrator else "keep (orchestrator)"
            lines.append(f"| `{fn.name}()` | {self.analysis.source_language} | **{target}** | ~{fn.energy_savings_percent:.0f}% | {fn.reason} |")

        lines += [
            "",
            "## Architecture",
            "```",
            f"{self.source_file.name}  (orchestrator — {self.analysis.source_language})",
        ]
        for fn in moved:
            stem = f"native_{fn.recommended_language.lower().replace('+', 'p').replace(' ', '_')}"
            lines.append(f"  └──► {stem}  [{fn.recommended_language}]  {fn.name}()")
        lines += [
            "```",
            "",
            "## How to Run",
            "```bash",
            "# Build native modules",
            "bash build.sh",
            "",
            "# Run exactly like the original",
            "./run.sh [original arguments]",
            "",
            "# Or with Docker",
            "docker compose build",
            "docker compose run graalvm-optimizer [original arguments]",
            "```",
            "",
            "## Paper Reference",
            "_Energy Efficiency Across Programming Languages_ — Pereira et al., SLE'17",
        ]
        (self.output_dir / "REPORT.md").write_text("\n".join(lines), encoding='utf-8')
